#!/bin/bash

# If rclone is already running (e.g., a long backup is in process), just bail.
PID_RCLONE=`pgrep rclone` 

if [ "$?" = 0 ] ; then
	echo "backup.devbox: rclone already running at pid $PID_RCLONE. There may be a long backup in process." 
	exit 1
fi


if [ "$1" = "dry-run" ] ; then
	rclone sync --dry-run -v --delete-excluded --exclude-from=/home/harry/.config/backup.exclude /home/harry/ delta-secret:
elif [ "$1" = "real" ] ; then
	rclone sync --skip-links -v --delete-excluded --exclude-from=/home/harry/.config/backup.exclude /home/harry/ delta-secret:
elif [ "$1" = "quiet" ] ; then
	rclone sync --skip-links --log-level ERROR --delete-excluded --exclude-from=/home/harry/.config/backup.exclude /home/harry/ delta-secret:
elif [ "$1" = "check" ] ; then
	rclone check --skip-links -v --size-only --exclude-from=/home/harry/.config/backup.exclude /home/harry/ delta-secret:
else
	echo "backup.devbox usage: backup.devbox { dry-run | real | quiet | check }"
	exit 1
fi
