#!/bin/bash

if [ "$#" -ne 2 ]; then
	echo "Usage: nasx {mount|umount} {harry|enc_harry|music}" 
	exit 1
fi

if [[ "$1" == "mount" ]]; then
	if grep -qs "/mnt/nasx/$2" /proc/mounts; then
		echo "Already mounted"
		exit 1
	fi
	sudo mount -t drvfs "\\\\nasx\\$2" "/mnt/nasx/$2"

elif [[ "$1" == "unmount" || "$1" == "umount" ]]; then
	sudo umount "/mnt/nasx/$2"

else
	echo "Usage: nasx {mount|umount} {harry|enc_harry|music}" 
fi
