#!/bin/bash

if [[ "$1" == "mount" ]]; then
	echo "OneDrive Mounted. Ctrl-C to unmount."
	rclone --vfs-cache-mode writes mount onedrive: ~/od

elif [[ "$1" == "unmount" || "$1" == "umount" ]]; then
	echo "not implemented"

else
	echo "Usage: od {mount|umount}" 
fi
